Repository unicef/kindly, pull requests merged in 2021-09, with the labels that each got.

#16 BLD: only allow POST, check for params in api
  api/Dockerfile
  api/api.py
  docs/development.md
Labels: enhancement

#19 DOC: add out of memory error
  docs/development.md
Labels: documentation

#20 BLD: cache the model into docker image
  .gitignore
  api/Dockerfile
  api/api.py
  api/get_model.py
  docs/development.md
Labels: enhancement

#22 BUG: get the right model!
  api/get_model.py
Labels: bug

#21 BUG: get remote mapping if local version missing
  api/api.py
Labels: bug

#23 MAINT: smaller docker image
  api/Dockerfile
  api/requirements.docker.txt
  api/requirements.txt
Labels: enhancement

#28 GitHub Action to push to DockerHub
  .github/workflows/main.yml
Labels: enhancement
